// src/app/privacy/page.tsx
"use client"; // Keep this if you have client-side interactions, though this page seems static

import React from 'react';
import styles from './PrivacyPage.module.css'; // Import the CSS module
import { Header } from '@/components/layout/Header'; // Adjust path if necessary
import { Footer } from '@/components/layout/Footer'; // Adjust path if necessary

export default function PrivacyPage() {
  const effectiveDate = "[Insert Date]"; // TODO: Replace with actual date
  const contactEmail = "[Insert Contact Email]"; // TODO: Replace with actual email

  return (
    <>
      <Header />
      <main className={styles.pageContainer}>
        <h1 className={styles.title}>Privacy Policy</h1>


        <p className={styles.paragraph}>
          Terapai ("we," "our," or "us") is committed to protecting the privacy and security of our users. This Privacy Policy explains how we collect, use, and safeguard the information you provide when using our application.
        </p>

        <section className={styles.section}>
          <h2 className={styles.sectionTitle}>1. Information We Collect</h2>
          <ul className={styles.list}>
            <li className={styles.listItem}><strong>Therapist Information:</strong> We collect your name, email, and UID from Firebase Authentication.</li>
            <li className={styles.listItem}><strong>Session Data:</strong> We temporarily store recorded audio for the sole purpose of transcription and note generation. Audio is automatically deleted after processing.</li>
            <li className={styles.listItem}><strong>Generated Notes:</strong> Summaries and transcripts are stored securely in Firestore and are only accessible to the authenticated user who created them.</li>
            <li className={styles.listItem}><strong>Consent Logs:</strong> When you begin a recording, we log that you’ve confirmed patient consent.</li>
          </ul>
        </section>

        <section className={styles.section}>
          <h2 className={styles.sectionTitle}>2. How We Use Your Information</h2>
          <ul className={styles.list}>
            <li className={styles.listItem}>To enable secure login and user identification.</li>
            <li className={styles.listItem}>To transcribe and summarize recorded therapy sessions.</li>
            <li className={styles.listItem}>To provide a record of consent for compliance.</li>
            <li className={styles.listItem}>To store and retrieve session notes generated by you.</li>
          </ul>
        </section>

        <section className={styles.section}>
          <h2 className={styles.sectionTitle}>3. Data Security</h2>
          <ul className={styles.list}>
            <li className={styles.listItem}>All data is encrypted in transit and at rest.</li>
            <li className={styles.listItem}>Audio files are deleted after transcription.</li>
            <li className={styles.listItem}>Access to data is strictly limited to the authenticated therapist.</li>
          </ul>
        </section>

        <section className={styles.section}>
          <h2 className={styles.sectionTitle}>4. Your Rights</h2>
          <ul className={styles.list}>
            <li className={styles.listItem}>You may delete your data at any time.</li>
            <li className={styles.listItem}>You can request a copy of your session data.</li>
            <li className={styles.listItem}>You may contact us to request permanent deletion of your account and data.</li>
          </ul>
        </section>

        <section className={styles.section}>
          <h2 className={styles.sectionTitle}>5. Changes to This Policy</h2>
          <p className={styles.paragraph}>
            We may update this policy periodically. Continued use of the service constitutes your acceptance of the changes.
          </p>
        </section>

        <section className={styles.section}>
          <h2 className={styles.sectionTitle}>Contact Us</h2>
          <p className={styles.paragraph}>
            If you have questions, contact us at: <a href={`mailto:${contactEmail}`} className={styles.contactLink}>{contactEmail}</a>
          </p>
        </section>
      </main>
      <Footer />
    </>
  );
}