

import React from 'react';

export default function PrivacyPage() {
  return (
    <main className="max-w-3xl mx-auto py-12 px-4">
      <h1 className="text-3xl font-bold mb-6">Privacy Policy</h1>

      <p className="mb-4">Effective Date: [Insert Date]</p>

      <p className="mb-4">
        TheraScript ("we," "our," or "us") is committed to protecting the privacy and security of our users. This Privacy Policy explains how we collect, use, and safeguard the information you provide when using our application.
      </p>

      <h2 className="text-xl font-semibold mt-8 mb-2">1. Information We Collect</h2>
      <ul className="list-disc pl-6 mb-4">
        <li><strong>Therapist Information:</strong> We collect your name, email, and UID from Firebase Authentication.</li>
        <li><strong>Session Data:</strong> We temporarily store recorded audio for the sole purpose of transcription and note generation. Audio is automatically deleted after processing.</li>
        <li><strong>Generated Notes:</strong> Summaries and transcripts are stored securely in Firestore and are only accessible to the authenticated user who created them.</li>
        <li><strong>Consent Logs:</strong> When you begin a recording, we log that you’ve confirmed patient consent.</li>
      </ul>

      <h2 className="text-xl font-semibold mt-8 mb-2">2. How We Use Your Information</h2>
      <ul className="list-disc pl-6 mb-4">
        <li>To enable secure login and user identification.</li>
        <li>To transcribe and summarize recorded therapy sessions.</li>
        <li>To provide a record of consent for compliance.</li>
        <li>To store and retrieve session notes generated by you.</li>
      </ul>

      <h2 className="text-xl font-semibold mt-8 mb-2">3. Data Security</h2>
      <ul className="list-disc pl-6 mb-4">
        <li>All data is encrypted in transit and at rest.</li>
        <li>Audio files are deleted after transcription.</li>
        <li>Access to data is strictly limited to the authenticated therapist.</li>
      </ul>

      <h2 className="text-xl font-semibold mt-8 mb-2">4. Your Rights</h2>
      <ul className="list-disc pl-6 mb-4">
        <li>You may delete your data at any time.</li>
        <li>You can request a copy of your session data.</li>
        <li>You may contact us to request permanent deletion of your account and data.</li>
      </ul>

      <h2 className="text-xl font-semibold mt-8 mb-2">5. Changes to This Policy</h2>
      <p className="mb-4">
        We may update this policy periodically. Continued use of the service constitutes your acceptance of the changes.
      </p>

      <h2 className="text-xl font-semibold mt-8 mb-2">Contact Us</h2>
      <p className="mb-4">
        If you have questions, contact us at: [Insert Contact Email]
      </p>
    </main>
  );
}
